var t1 = [10, "Jane", true];
console.log(t1);
var add = [10, "Ajay"];
console.log(add);
var product = [101, "Speakers", 2000];
console.log("Product Id : " + product[0]);
product.push(102, "Bags", 1400);
console.log(product);
product.push(100, "Shoes", 1000);
console.log(product);
console.log(product.pop());
